/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/**
 * Processor Core(Nhân-lõi xử lý): là công cụ tính toán cơ bản của bộ vi xử lý, bao gồm thanh ghi ALU(nơi tính
 * toán diễn ra), các barrel shifter(bộ chuyển động), các thanh ghi khác để thao tác dữ liệu, và đặc biệt là các
 * hàm chức năng để theo dõi trạng thái thực thi của lõi(trình giải mã-decoder).
 *
 * Processor(Vi xử lý): bao gồm lõi xử lý và các thanh ghi, thiết bị hỗ trợ xung quanh.
 * Ngoài ra, vi xử lý cũng có thể gọi là CPU(bộ vi xử lý trung tâm)
 *
 * Microcontroller(Vi điều khiển): bao gồm CPU, các thanh ghi ngoại vi, các port ngoại vi, nguồn, thạch anh,
 * thanh ghi RAM, ROM,...
 *
 * Các nhà sản xuất Processor tùy vào mục đích sẽ tạo ra các kiến trúc riêng cho từng dòng vi xử lý.
 * Ví dụ dòng ARM Cortex M3/4., các dòng dùng cho mục đích điện thoại, CLOUD, IOT,...
 *
 * Các nhà sản xuất bo mạch điều khiển: đầu tiên họ sẽ mua các Processor-CPU, sau đó sẽ kết hợp CPU đó với các
 * thiết bị ngoại vi theo thiết kế riêng từng hãng để tạo ra một bo mạch vi điều khiển riêng từng hãng.
 * Ví dụ: dòng vi điều khiển PIC, AVR, MSP,..
 *
 * ==>Vì vậy, khi tìm hiểu một vi điều khiển bất kỳ ta cần phải tham khảo sơ đồ khối(block diagram) của vi điều khiển đó
 * để tìm hiểu và nắm được cấu trúc và các chức năng có thể điều khiển của nó.
 */

/**
 * Vi điều khiển sử dụng trong khóa học là STM32407VET6 32bit
 * Processor: ARM cortex M4 with FPU(Floating Point Unit)
 * Ngoài ra còn bao gồm các thạch anh((MHz), các nút nhấn, các port pin IO,..
 * Có cung cấp tính năng debugger với chuẩn STLink/V2-A
 */

/**
 * Feature of the Cortex M0/M3/M4 (Tính năng của các dòng vi xử lý Cortex)
 * 1) Chế độ hoạt động của bộ xử lý.
 * 2) Các mức truy cập khác nhau của bộ vi xử lý.
 * 3) Các thanh ghi của bộ vi xử lý.
 * 4) Tìm hiểu về thiết kế Banked Stack của bộ vi xử lý.
 * 5) Ngoại lệ(exceptions) và cách xử lý ngoại lệ.
 * 6) Xử lý ngắt (interrupt handling)
 * 7) Tìm hiểu Bus Interface và Bus Matrix
 * 8) Tìm hiểu về bộ nhớ và kiến trúc bộ nhớ (memory architecture), dải bit (bit banding), memory map của bộ vi xử lý.
 * 9) Bộ xử lý endiannness
 * 10) Truyền dữ liệu liên kết(aligned) và không liên kết(unAligneđ).
 * 11) Bootloader(bộ tải khởi động) and IAP (bộ lập trình mã nhị phân)
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>

int main(void)
{
    /* Loop forever */
	printf("Hello World\n");
	for(;;);
}
