/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

/*
 * Sử dụng từ khóa 'volatile' với ISP_Interrupt Service Routine(ngắt)
 * */
#include <stdint.h>
#include <stdio.h>

//global shared variable between main code and ISR
uint8_t volatile g_button_pressed = 0;   //biến toàn cục xử lý ngắt

uint32_t g_button_press_count =0;

void button_init(void);

//Thiết lập các cấu hình địa chỉ các port sử dụng với từ khóa 'volatile'
uint32_t volatile *pEXTTIPendReg			= (uint32_t*) (0x40013C00 + 0x14);
uint32_t volatile *pClkCtrlReg				= (uint32_t*) (0x40023800 + 0x30);
uint32_t volatile *pClkCtrlRegApb2			= (uint32_t*) (0x40023800 + 0x44);
uint32_t volatile *pGPIOAModeReg 			= (uint32_t*) (0x40020000 + 0x00);
uint32_t volatile *pEXTIMaskReg 			= (uint32_t*) (0x40013C00 + 0x00);
uint32_t volatile *pEXTTIEdgeCtrlReg		= (uint32_t*) (0x40013C00 + 0x08);
uint32_t volatile *pNVICIRQEnReg 			= (uint32_t*) 0xE000E100;

int main(void)
{
	button_init();

	while(1)
	{
		//Disable interrupt
		*pEXTIMaskReg &= ~( 1 << 0);

		if(g_button_pressed){   //nếu có nút ngắt được nhấn

			//Some delay until button debouncing gets over
			for(uint32_t volatile i=0;i<500000/2;i++);  //delay chương trình

			g_button_press_count++;

			printf("Button is pressed : %lu\n",g_button_press_count);

			g_button_pressed = 0;	//reset lại giá trị biến
		}

		//Enable interrupt
		*pEXTIMaskReg |= ( 1 << 0);
	}

	//Kết quả: Khi chưa thiết lập từ khóa 'volatile' cho các địa chỉ thanh ghi thì khi chạy với mức
	//tối ưu hóa càng cao thì việc nhấn nút ngắt càng xử lý chậm và không chính xác. Xuất hiện tình trạng
	//nhiệm vụ ngắt không đc thực hiện nhưng giá trị biến g_button_press_count vẫn tăng lên. Nguyên nhân là
	//tối ưu hóa trình biên dịch cho rằng biến ngắt là một biến không đc sử dụng trong chương trình,
	//còn biến g_button_press_count là một biến sử dụng do nó nằm trong một biểu thức tính toán.

	//Và sau khi thêm từ khóa 'volatile' vào thì dù ở mức tối ưu hóa nào thì trình biên dịch
	//đều sẽ thực hiện lệnh ngắt chính xác.
}

//Cấu hình địa chỉ thanh ghi cho nút nhấn
void button_init(void)
{

  *pClkCtrlReg |= ( 1 << 0);

  *pClkCtrlRegApb2 |= ( 1 << 14);

  *pEXTTIEdgeCtrlReg |= ( 1 << 0);

  *pEXTIMaskReg |= ( 1 << 0);

  *pNVICIRQEnReg |= ( 1 << 6);

}

/* This is button interrupt handler-hàm xử lý nút nhấn ngắt_interrupt*/
void EXTI0_IRQHandler(void)
{
	//Make this flag SET . if button pressed
  g_button_pressed = 1;

  *pEXTTIPendReg |= ( 1 << 0);
}


