/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/**
 * Viết một chương trình(program) để đầu ra HSI clock trên pin vi điều khiển(nghĩa là HSI clock là main system clock
 * cho các pin của microcontroller)- Ko sử dụng CubeMx để cấu hình(V40)
 *
 * Peripheral: GPIOA
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdint.h>

//Định địa chỉ thanh ghi cấp xung clock
//Xác định address RCC_Register dùng để kích hoạt xung clock
//Vì ta cần cấu hình "HSI là main systemclock" nên ta cần sử dụng bit field "MCO1" trên thanh ghi control nó là
//RCC Clock configuration register(RCC_CFGR)
//Đọc datasheet -> 7.3 RCC Clock -> 7.3.3 RCC_CFGR  để xác địa chỉ cần thiết và bit cần kích hoạt
#define RCC_BASE_ADDR              0x40023800UL		//Memory Map ->address base RCC_Register
#define RCC_CFGR_REG_OFFSET        0x08UL			//address offset-phần bù(RCC Clock configuration register)
#define RCC_CFGR_REG_ADDR          (RCC_BASE_ADDR + RCC_CFGR_REG_OFFSET ) //address official RCC_CFGR

//Định địa chỉ thanh ghi GPIOA
#define GPIOA_BASE_ADDR            0x40020000UL

int main(void)
{
	uint32_t *pRccCfgrReg =  (uint32_t*) RCC_CFGR_REG_ADDR;	//biến chứa address RCC_CFGR

	//B1. Configure(cấu hình) the RCC_CFGR MCO1 bit fields to select HSI as clock source
	//B1. Cấu hình trường bit RCC_CFGR MCO1 để chọn HSI làm nguồn xung nhịp
	*pRccCfgrReg &= ~(0x3 << 21); //clear 21 and 22 bit positions -> đưa 2 bit về 00
	//MCO1 thuộc 2 bit là 21 và 22 và ta có 4 lựa chọn cặp số bit và theo đề bài tạo HSI clock nên cặp
	//số cần thiết là 00:HSI clock select
	//0x3 = 0011 -> cấu hình 2 bit liên tiếp nhau bắt đầu từ vị trí bit đc dịch tới.

	//Configure MCO1 pre-scaler(bộ chia) - Cấu hình MCO1 Prescaler(Bộ đếm hoặc bộ chia tần số đầu vào MCO1)
	*pRccCfgrReg |= ( 1 << 24);
	*pRccCfgrReg |= ( 1 << 25);
	//*pRccCfgrReg |= ( 1 << 26);
	//MCO1 prescaler đc quản lý bởi bit 24,25,26 của thanh ghi RCC_CFGR
	//Với bit 24[0]: vô hiệu hóa, 24[1] : cho phép chia
	//100: chia 2, 101: chia 3, 110 chia 4, 111 chia 5
	//Ta muốn thiết lập bộ chia 4 nên sẽ set bit 25[1],26[0](giữ nguyên)

	//B2. Configure PA8 to AF0 mode to behave as MCO1 signal
	//B2. Định cấu hình chế độ PA8 thành AF0 để hoạt động như tín hiệu MCO1
/*
 * You are not expected to understand the below codes for the time being because these codes are related to GPIO configurations,
 * which will be covered in later sections of this course.
 *
 * V40: Hiện tại bạn không thể hiểu được các mã bên dưới vì các mã này liên quan đến cấu hình GPIO,
 * sẽ được đề cập trong các phần sau của khóa học này.
 */

	//a ) Enable the peripheral clock for GPIOA peripheral
	//a) Kích hoạt đồng hồ ngoại vi cho thiết bị ngoại vi GPIOA
	//0x30: phần bù ofset của phần RCC_AHB1 vì GPIOA kết nối vxl thông qua AHB1 Bus
	 uint32_t *pRCCAhb1Enr = (uint32_t*)(RCC_BASE_ADDR + 0x30);
	*pRCCAhb1Enr |= ( 1 << 0); 			//Enable GPIOA peripheral clock - Kích hoạt đồng hồ ngoại vi GPIOA
										//Enable Clock của GPIOA nằm ở bit0 của thanh ghi RCC_AHB1

	//b ) Configure the mode of GPIOA pin 8 as alternate function mode
	//b ) Cấu hình chế độ của GPIOA chân 8 làm chế độ chức năng thay thế
	uint32_t *pGPIOAModeReg = (uint32_t*)(GPIOA_BASE_ADDR + 00);
	*pGPIOAModeReg &= ~( 0x3 << 16); //clear
	*pGPIOAModeReg |= ( 0x2 << 16);  //set

	//c ) Configure the alternation function register to set the mode 0 for PA8
	//c ) Cấu hình thanh ghi chức năng thay thế để đặt chế độ 0 cho PA8
	uint32_t *pGPIOAAltFunHighReg = (uint32_t*)(GPIOA_BASE_ADDR + 0x24);
	*pGPIOAAltFunHighReg &= ~( 0xf << 0);

	for(;;);

	//Tiến hành Run and debug và quan sát kết quả ở cửa sổ Register
}
