/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

/*
 * Volatile *
 * Định nghĩa:
 * Là một kiểu từ khóa hạn định, giới hạn(qualifier) để đặc tả các biến trong ngôn ngữ C.
 * Vai trò sử dụng giống với từ khóa 'const' nhưng cách sử dụng khác nhau.
 * Được dùng để hướng dẫn trình biên dịch không được gọi bất kỳ tối ưu nào trên hoạt động của biến
 * (Hoạt động của biến là hoạt động đọc và ghi)
 * Thông báo cho trình biên dịch rằng giá trị biến có thể thay đổi bất cứ lúc nào mà không phải từ
 * lập trình viên thay đổi. Vì vậy, trình biên dịch sẽ tắt tối ưu hóa các hoạt động read-write trên
 * các biến được khai báo băng cách sử dụng từ khóa 'volotile'
 * Từ khóa 'volotile' rất hữu ích trong mã hệ thống nhúng để giảm lỗi
 *
 * Cách sử dụng:
 * Sử　dụng từ khóa 'volatile' khi biến có khả năng thay đổi bất ngờ về giá trị biến.
 * Vd: giá trị biến đọc chân pin PA0 thường thay đổi bất ngờ, người dùng có thể thay đổi
 * giá trị vào của biến đọc chân pin bất cứ lúc nào
 * Một số trường hợp cụ thể:
 * + Khi bạn làm việc với bộ nhớ được ánh xạ tới các thanh ghi ngoại vi của các bộ vi điều khiển.
 * + Khi bạn phải làm nhiều task vụ như truy cập các biến global trong một ứng dụng đa luồng RTOS.
 * + Khi một biến global được sử dụng để chia sẻ dữ liệu giữa main code và mã ISR.
 * ISR_Interrupt Service Routine(ngắt)
 *
 * Cách khai báo:
 * +Cách 1: volatile data (dùng cho biến)
 *     kiểu_biến volatile tên_biến;    hoặc    volatile kiểu_biến tên_biến
 * vd: uint8_t volatile my_data;       hoặc    volatile uint8_t my_data;
 *
 * +Cách 2: non-volatile pointer to volatile data (dùng cho con trỏ-hay sử dụng trong embedded)
 *     kiểu_biến volatiole *tên_con_trỏ
 * vd: uint8_t volatile *pStatusReg
 * Cách này thường được sử dụng trong trường hợp 1(cần ánh xạ đến các thanh ghi ngoại vi)
 * */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdint.h>

int main(void)
{
	//Bật tối ưu hóa tuần tự ở các mức để và debug, sau đó vào xem kết quả ở thanh disassembly

	//Vd1: khai báo các biến không sử dụng từ khóa 'volatile'
//	uint8_t data1;
//	uint8_t data2;
	//Ở vd1, khi ta đặt mức tối ưu hóa lên O1 thì trình biên dịch sẽ bỏ qua các và lệnh gán giá trị
	//Nguyên nhân vì trình biên dich nhận thấy đây là các biến chưa được sử dụng trong chương trình
	//Để biến được coi là sử dụng thì biến đó cần được sử dụng trong chương trình, là các thành phần
	//trong một phép toán, một đối số(argumnet) gọi hàm.

	//Vd2: khai báo các biến sử dụng từ khóa 'volotile'
	uint8_t volatile data1;
	uint8_t volatile data2;
	//Tất cả lệnh liên quan đến biến có khai báo 'volotile' sẽ đc thực hiện dù có thực hiện tối ưu hóa
	//mức bao nhiêu

	data1 = 50;

	data2 = data1;

	data2 = data1;

	for(;;);
}
