/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/**
 * Một số kiến thức liên quan đến String_Chuỗi (S30_V186)
 *
 * Phân biệt giữa con trỏ Chuỗi(literal) và Chuỗi thông thường
 * + Chuỗi : char msg1[] = "hello"  -> Value này sẽ đc lưu trong Stack of RAM
 * Khi thay đổi giá trị: msg1[0] = 's';   -> cho phép
 *
 * + Con trỏ Chuỗi: char *msg2[] = "hello"  -> Value này sẽ đc lưu trong ROM(cụ thể là bộ nhớ Flash)
 * Khi thay đổi giá trị: msg2[0] = 's';   -> KHÔNG cho phép thay đổi value trong bộ nhớ ROM, chuỗi hằng
 */

#include <stdint.h>		//thư viện định dạng khai báo biến

int main(void)
{
	char msg1[] = "Hello how are you";
	char *pmsg2[] = "fastbitlab.com";  //tương đương một chuỗi hằng

	printf("Message is : %s\n", msg1);
	printf("Message is : %s\n", pmsg2);

	printf("Address of 'msg1' variable : %p\n", &msg1);   //Value1_msg1
	printf("Value of 'msg1' is : %p\n", msg1);				//Value2_msg1

	printf("Address of 'msg1' variable : %p\n", &pmsg2);
	printf("Value of 'msg1' is : %p\n", pmsg2);

	msg1[0] = 'b';
	//pmsg2[0] = 'b';   //không cho phép thay đổi chuỗi hằng

	//->Tùy vào vi xử lý mà value1==value2==địa_chỉ_x

	for(;;);
}

/**
 * Trong ngôn ngữ lập trình C, fflush() là một hàm dùng để xóa bộ đệm của một luồng dữ liệu (stream),
 * giúp đảm bảo rằng dữ liệu đã được ghi vào luồng sẽ được đưa ra ngoài ngay lập tức.
 * Trong trường hợp đặc biệt khi ta muốn đảm bảo rằng dữ liệu được hiển thị trên màn hình ngay lập tức,
 * thì hàm fflush(stdout) có thể được sử dụng để đẩy bộ đệm của stdout (luồng đầu ra tiêu chuẩn) ra ngoài.
 * Ví dụ, khi bạn ghi dữ liệu vào stdout bằng hàm printf(), các ký tự trong chuỗi định dạng printf()
 * sẽ được lưu trong bộ đệm và chỉ được hiển thị trên màn hình khi bộ đệm đầy hoặc khi một dòng mới
 * được in ra. Tuy nhiên, nếu bạn muốn hiển thị ký tự ngay lập tức thay vì chờ bộ đệm đầy, bạn có
 * thể sử dụng fflush(stdout) để đẩy bộ đệm của stdout ra ngoài.
 * Lưu ý rằng việc sử dụng fflush() không được khuyến khích trong các ứng dụng thời gian thực hoặc
 * trong các ứng dụng đòi hỏi hiệu suất cao, vì việc xóa bộ đệm sẽ làm giảm hiệu suất của ứng dụng.
 */

/**
 * Điều kiện nhập chuỗi
 * vd: char name[30]; scanf("%[^s]s",name);
 * Yêu cầu nhập chuỗi đến khi nào có ký tự 's' xuất hiện
 * vd2: char name[30]; scanf("%[^\n]s",name); -> Nhập chuỗi đến khi có ký tự xuống dòng
 */


