/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/
/*
 * Sử dụng 'volatile' và 'const' trong khai báo biến
 * Ở trường hợp này ta sẽ cộng tất cả các thông báo chức của cả 'const' và 'volatile'
 *
 * vd1: uint8_t volatile *const pReg = (uint8_t*)0x40000000; ->cho phép thay đổi giá trị của địa
 * chỉ mà con trỏ đang giữ đồng thời thực hiện các lệnh có chứa biến này nếu sử dụng tối ưu hóa
 *
 * vd2: uint8_t const volatile *const pReg = (uint8_t*)0x40000000; -> Không cho phép thay đổi giá trị của
 * địa chỉ cũng như địa chỉ mà con trỏ đang chứa đòng thời thực hiện các lệnh có chứa biến này nếu sử dụng
 * tối ưu hóa
 *
 * Được sử dụng trong các trường hợp chỉ đc phép đọc(read-only) đối với các buffer hoặc địa chỉ dễ bị thay
 * đổi data bất ngờ
 * */

//Trong vd này, thì tùy thuộc vào chức năng cấu hình địa chỉ mà ta sử dụng 'volatile' hay 'const'
#include<stdint.h>

int main(void)
{
	//Cấu hình địa chỉ cho vd1
	uint32_t volatile *const pClkCtrlReg =   (uint32_t*)0x40023830;
	uint32_t volatile *const pPortDModeReg = (uint32_t*)0x40020C00;
	uint32_t volatile *const pPortDOutReg =  (uint32_t*)0x40020C14;

	uint32_t volatile *const pPortAModeReg = (uint32_t*)0x40020000;
	uint32_t const volatile *const pPortAInReg =   (uint32_t*)0x40020010; //vd2


	//enable the clock for GPOID , GPIOA peripherals in the AHB1ENR
	*pClkCtrlReg |= ( 1 << 3);
	*pClkCtrlReg |= ( 1 << 0);

    //configuring PD12 as output
	*pPortDModeReg &= ~( 3 << 24);
	//make 24th bit position as 1 (SET)
	*pPortDModeReg |= ( 1 << 24);

	//Configure PA0 as input mode (GPIOA MODE REGISTER)
	*pPortAModeReg &= ~(3 << 0);

	while(1)
	{
		//read the pin status of the pin PA0 (GPIOA INPUT DATA REGISTER)
		uint8_t  pinStatus = (uint8_t)(*pPortAInReg & 0x1); //zero out all other bits except bit 0

		if(pinStatus){
			//turn on the LED
			*pPortDOutReg |= ( 1 << 12);
		}else{
			//turn off the LED
			*pPortDOutReg &= ~( 1 << 12);
		}
	}

}
