/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/**
 * V41:Viết một chương trình(program) để đầu ra HSE clock trên pin vi điều khiển(nghĩa là HSE clock là main system clock
 * cho các pin của microcontroller)
 * Peripheral: GPIOA
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdint.h>

//Định địa chỉ thanh ghi cấp xung clock
#define RCC_BASE_ADDR              0x40023800UL	//địa chỉ cơ sở thanh ghi RCC

#define RCC_CFGR_REG_OFFSET        0x08UL	//phần bù thanh ghi RCC_CFGR(RCC Clock configuration register)

#define RCC_CR_REG_OFFSET          0x00UL	//Phần bù thanh ghi RCC_CR

//Thanh ghi RCC_CFGR(RCC Clock configuration register) chứa bit 0 kích hoạt HSE thành System Clock
#define RCC_CFGR_REG_ADDR          (RCC_BASE_ADDR + RCC_CFGR_REG_OFFSET )	//address official RCC_CFGR

//Thanh ghi RCC_CR(RCC clock control register) chứa bit HSE_ON(Bit 16)
#define RCC_CR_REG_ADDR            (RCC_BASE_ADDR + RCC_CR_REG_OFFSET )		//address official RCC_CR

#define GPIOA_BASE_ADDR            0x40020000UL		//địa chỉ cơ sở thanh ghi control GPIOA

int main(void)
{

	uint32_t *pRccCrReg = (uint32_t*)RCC_CR_REG_ADDR;		//biến chứa addres RCC_CR
	uint32_t *pRccCfgrReg = (uint32_t*)RCC_CFGR_REG_ADDR;	//biến chứa addres RCC_CFGR

	//1.Enable the HSE clock using HSEON bit field (RCC_CR)
	*pRccCrReg |= ( 1 << 16);

	//2. Wait until HSE clock from the external crystal stabilizes (only if crystal is connected )
	//Bit17 của RCC_CR chứa bit xác định HSE ocillator có sẵn sàng hay ko(0:not ready; 1: ready)
	while( ! (*pRccCrReg & ( 1 << 17) ) );

	//& ( 1 << 17 ): Đây là phép toán AND bit-wise. Khi thực hiện phép AND bit-wise giữa giá trị của
	//thanh ghi và số này, nếu bit thứ 17 của thanh ghi bằng 1 thì kết quả của phép AND cũng bằng 1,
	//ngược lại sẽ bằng 0.

	//Code này sử dụng vòng lặp while để kiểm tra giá trị của bit thứ 17 trong thanh ghi RCC_CR.
	//Bit này được sử dụng để kiểm tra trạng thái của bộ dao động chính của vi điều khiển.
	//Nếu bit này có giá trị 0, thì bộ dao động chính chưa được bật. Vòng lặp sẽ tiếp tục
	//cho đến khi bit này có giá trị 1, cho biết rằng bộ dao động chính đã được bật.

	//3. Switch the system clock to HSE (RCC_CFGR)
	*pRccCfgrReg |= ( 1 << 0);
	//Để chuyển sang HSE clock thì cần sử dụng bit field SW[1:0] của RCC_CFGR


	/**************4.Do MCO1 settings to measure it*********************/

	//4.1. Configure the RCC_CFGR MCO1 bit fields to select HSE as clock source
	*pRccCfgrReg |= ( 1 << 22); //clear 21 and SET 22 (HSE oscillator clock selected)

	//Configure MCO1 prescaler // divisor as 4 //thiết lập bộ chia 4
	*pRccCfgrReg |= ( 1 << 24);
	*pRccCfgrReg |= ( 1 << 25);
	//*pRccCfgrReg |= ( 1 << 26);
	//MCO1 prescaler đc quản lý bởi bit 24,25,26 của thanh ghi RCC_CFGR
	//Với bit 24[0]: vô hiệu hóa, 24[1] : cho phép chia
	//100: chia 2, 101: chia 3, 110 chia 4, 111 chia 5
	//Ta muốn thiết lập bộ chia 4 nên sẽ set bit 25[1],26[0](giữ nguyên)


	//4.2. Configure PA8 to AF0 mode to behave as MCO1 signal
	/*
	 * You are not expected to understand the below codes for the time being
	 * because these codes are related to GPIO configurations,
	 * which will be covered in later sections of this course.
	 */

	//a ) Enable the peripheral clock for GPIOA peripheral
	 uint32_t *pRCCAhb1Enr = (uint32_t*)(RCC_BASE_ADDR + 0x30);	//0x30: address offset of RCC_AHB1ENR
	*pRCCAhb1Enr |= ( 1 << 0); 					//Enable GPIOA peripheral clock use bit field GPIOAEN[0] of RCC_AHB1ENR

	//b ) Configure the mode of GPIOA pin 8 as alternate function mode - Định cấu hình chế độ của chân 8 của GPIOA làm chế độ chức năng thay thế
	uint32_t *pGPIOAModeReg = (uint32_t*)(GPIOA_BASE_ADDR + 00);
	*pGPIOAModeReg &= ~( 0x3 << 16); //0x3=0011 -> bit [17:16] is clear
	*pGPIOAModeReg |= ( 0x2 << 16);  //0x2=0010 -> bit [17] is set

	//c ) Configure the alternation function register to set the mode 0 for PA8
	uint32_t *pGPIOAAltFunHighReg = (uint32_t*)(GPIOA_BASE_ADDR + 0x24);  //0x24: address offset of GPIOx_AFRH(8.4.10)
	*pGPIOAAltFunHighReg &= ~( 0xf << 0);		//0xf=1111 -> Enable 4 bit field AFRH8[3:0]

	for(;;);
}

