/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/
/**
 * Cách hoạt động xử lý code của processor:
 *
 * Chú y: + Trong bài chỉ hướng dẫn cách hoạt động của các chế độ trong vi xử lý, còn chi tiết sẽ được giới thiệu
 * ở các bài sau.
 * + Để có thể quan sát được sự thay đổi giữa 2 chế độ Thread(0) và Handler(1) trong vi xử lý thì khi thực thi ta sẽ
 * vào chế độ Register -> thanh ghi "xpsr" -> 6 bit cuối của chế đọ "Binary"
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdio.h>
#include<stdint.h>

/* This function executes in THREAD MODE of the processor
 * Hmà này vẫn nằm trong trong luồng xử lý bình thường của vi xử lý*/
void generate_interrupt()
{
	//Thiết lập đăng ký  địa chỉ thanh ghi của chương trình ngắt muốn sử dụng
	uint32_t *pSTIR  = (uint32_t*)0xE000EF00;
	uint32_t *pISER0 = (uint32_t*)0xE000E100;

	//enable IRQ3 interrupt   //cho phép chế độ ngắt của thanh ghi hoạt động
	*pISER0 |= ( 1 << 3);

	//generate an interrupt from software for IRQ3  //kích hoạt chế độ ngắt bằng phần mềm
	*pSTIR = (3 & 0x1FF); 

}

/* This function executes in THREAD MODE of the processor */
/*
 * Thực thi hàm main đầu tiên khi code debug
 * Hàm main khi bắt đầu sẽ luôn hoạt động ở chế độ Thread của vi xử lý
 */
int main(void)
{
	printf("In thread mode : before interrupt\n");

	generate_interrupt();

	printf("In thread mode : after interrupt\n");

	for(;;);
}

/* This function(ISR) executes in HANDLER MODE(	*pSTIR ) of the processor
 * Chức năng này (ISR) thực thi trong CHẾ ĐỘ XỬ LÝ ( *pSTIR ) của bộ xử lý
 * Khi chế độ ngắt đc kích hoạt thì core sẽ chuyển sang hoạt động chế độ handler_mode và đồng thời kích hoạt
 * hàm RTC_WKUP_IRQHandler thực thi.
 * */
void RTC_WKUP_IRQHandler(void)
{
	printf("In handler mode : ISR\n");
}

