/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*
 * Tính địa chỉ cho các bước bật sáng led:

Address of clock control register(AHB1ENR)
0x40023800+0x30 => 	0x40023830

Address of the GPIO mode register (used to control mode)
0x40020C00 + 0x00 	=>	0x40020C00

Address of the GPIO output data register (used to wroite)
0x40020C00 + 0x14  =>  0x40020C14
*/

/*
 * Tiến trình thực hiện việc bật tắt led
 * B1: Cần xác định cổng GPIO là ngoại vi được sử dụng để kết nối với đèn LED
 * Ở bài này ta sẽ sử dụng port GPIOD
 *
 * B2: Cần xác định pin GPIO muốn sử dụng
 * Ở bài này ta sẽ sử dụng pin 12 của port GPIOD
 *
 * B3: Kích hoạt ngoại vi GPIO(Enable the clock)
 * Có nghĩa là: theo mặc định,đa số các pin port sẽ đều ở trạng thái ngủ đông và cần chờ một xung clock
 * tín hiệu để kích(cho phép) pin đó hoạt động.
 * Lưu ý: bạn sẽ ko sử dụng được điều khiển ngoại vi pin cho đến khi bạn kích hoạt xung clock
 *
 * B4: Định cấu hình đầu ra cho chân pin(viết code thiết lập chân đó điều khiển tác dụng gì )
 * vd: muốn chân đó là chân output, hoặc input hoặc chân nhận tín hiệu analog
 * Vì vậy cần dựa vào datasheet để cấu hình cho pin port
 *
 * B5: Write to the GPIO pin (thiết lập điều khiển pin đã chọn điều khiển led)
 * 1(high) tạo chân pin GPIO ở mức HIGH(3.3V) - sáng
 * 0(high) tạo chân pin GPIO ở mức HIGH(3.3V) - tắt
 * */

#include <stdint.h>		//thư viện định dạng khai báo biến

int main(void)
{
	//Xác định địa chỉ thanh ghi ban đầu các thành phần cần điều khiển
    uint32_t *pClkCtrlReg = (uint32_t*)0x40023830;    //bước 3: đăng ký clock
    //Giải thích cách lấy địa chỉ thanh ghi clock
    //Địa chỉ thanh ghi Rigister and Clock(lấy xung clock) trong Memory map là 0x40023800
    //Và vì port D kết nối với memory map thông qua thanh ghi AHB1 có địa chỉ là 0x30
    //Địa chỉ của xung clock cần lấy cho port D là 0x40023830+0x30 = 0x40023830
    //Tại sao lại phép cộng: Memory map có địa chỉ là từ  0x40023800 đến 0x40023BFF
    //Mà thanh ghi AHB1 thuộc Memory map nên địa chỉ thanh ghi AHB1 sẽ nằm từ 0x40023800 đến 0x40023BFF
    //Và theo datasheet thì ta có Address offset(địa chỉ phần bù) của AHB1 là 0x30
    //Có nghĩa là cần lấy địa chỉ gốc thanh ghi RCC(0x40023800) + với phần bù 0x30
    //sẽ cho ra địa chỉ thanh ghi AHB1 nằm trên Memory map

    //Việc ép kiểu con trỏ ở đây để chương trình xác định đây là dãy số địa chỉ cần sử dụng
    //để gián tiếp mở khóa xung clock sử dụng cho port D

    uint32_t *pPortDmodeReg = (uint32_t*)0x40020C00;	//bước 4: cấu hình port sử dụng (chức năng của chân pin)
    //0x40020C00 : địa chỉ cở sở của port D (tìm trong datasheet)
    //vì trong port D sẽ chứa nhiều thanh ghi chức năng khác nhau nên cần xác định địa chỉ thanh ghi chức
    //năng mà ta muốn điều khiển
    //Ở đây ta muốn tìm địa chỉ thanh ghi để đăng ký kích hoạt chế độ điều khiển port-thiết lập chức năng chân pin
    //Và địa chỉ phần bù của thanh ghi này là 0x00
    //=> Địa chỉ thanh ghi cần sử dụng là: 0x40020C00 + 0x00 = 0x40020C00

    //Thêm: Mở datashet tìm phần đăng ký cấu hình cho port GPIO(phần 8.4.1)
    //Có thể thiết lập 4 chức năng cho 1 pin(mỗi port GPIO có 16 pin, 1pin chiếm 2 bit_có 32 bit từ 0->31)
    //00: input and reset ;  01: output  ;  10: chức năng thay thế   ;   11: tín hiệu analog

    uint32_t *pPortDoutReg = (uint32_t*)0x40020C14;			//bước 5: cấu hình địa chỉ port làm output
    //Ta sẽ thiết lập port ở chế độ output nên ta sẽ tìm và đăng ký thanh ghi có chức năng này
    //Địa chỉ phần bù: 0x14 -> địa chỉ cần đăng ký 0x40020C00 + 0x14 = 0x40020C14
    //Vì ta sẽ điều khiển đèn led LD4 và theo sở đồ khối thì LD4 thuộc chân pin số 12
    //trong GPIO thì pin 12 sẽ lấy bit 24 và bit 25



    //I. Su dung PP mat na bit
    //1.Bat dong ho cho thiet bi ngoai vi AHB1ENR
    //Cách viết 1:
    uint32_t temp = *pClkCtrlReg;
    temp = temp | 0x08;          //dung mat na bit  //modify  //su dung  OR để nâng bit4 lên 1 của dãy 32 bit
    *pClkCtrlReg = temp;		//write back

    //Cách viết 2:
    //*pClkCtrlReg = *pClkCtrlReg | 0x08;

    //cách viết 3
    //*pClkCtrlReg |= 0x08

    //Giải thích: Ở đây ta muốn yêu cầu cấp 1 xung clock(bit lên 1) cho port D
    //Theo datasheet thì địa chỉ cấp xung clock port D trong pClkCtrlReg nằm ở bit thứ 4 trong 32 bit
    //Ta sẽ đưa bit thứ 4 đó lên 1 và cho rằng các bit còn lại đều 0
    //Để làm được điều này thì ta cần quy đổi tính toán bit một chút:
    //Tất cả bit đều tắt:     0000 0000 0000 0000 0000 0000 0000 0000  (bit 4 là 0)
    //Dùng pp mặt nạ bit, ở dây ta cho nó OR với 1 dãy số bit mà ở ta muốn có vị trí nhảy lên 1
    //Và dễ nhất là cho nó OR với  0000 1000 = 0x08 để vị trí bit 4 nhảy lên 1

    //						  0000 0000 0000 0000 0000 0000 0000 0000  (bit 4 là 0)
    //											|(OR)
    //														0000 1000  (0x08)
    // -> Ta có dãy nhị phân: 0000 0000 0000 0000 0000 0000 0000 1000  (bit 4 đã lên 1)
    // -> Thập lục phân:       0     0    0    0    0    0    0    8

    //2.Cau hinh che do chan IO lam dau ra
    //Mặc định ban đầu tất cả 32 bit đều ở trạng thái 0
    //a.clear(reset) the bit 24 and 25, với cấu hình chân 00, xóa các chức năng cũ mà có thể đã thiết lập trước đó
    *pPortDmodeReg &= 0xFCFFFFFF;   //dung phep AND nang tat ca bit len 1 trừ 2 bit bit 24 va 25
    //1111 1100 1111 1111 1111 1111 1111 1111
    // F    C    F    F    F    F    F    F

    //b. set bit 24 len 1, đặt chế độ output cho chân pin 12 của port D(yêu cầu cho phép sử dụng pin 12)
    *pPortDmodeReg |= 0x01000000;		//dung phep OR nang 1 bit
    //0000 0001 0000 0000 0000 0000 0000 0000
    // 0    1    0    0    0    0    0    0
    //Giải thích: pin 12 port D thuộc 2 bit là 25 và 24, để thiết lập output cho pin này thì theo datasheet
    //thì cần thiết lập bit 25,24 lần lượt là 01.

    //3. Set output chan 12 GPIO len 1 cho LED sáng
    *pPortDoutReg |= 0x1000;
    //0001 0000 0000 0000 		(pin 12 lên 1, pin thì chỉ có 16 pin)
    // 1    0    0    0

    //II. Su dung phuong phap dich bit(tham khảo C19_Bitwise shift operator: phương pháp dịch bit)
    //1.Bat dong ho cho thiet bi ngoai vi AHB1ENR set bit 3 lên 1 (địa chỉ bit sẽ chạy từ 0->31)
//    *pClkCtrlReg |= (1<<3); //= *pClkCtrlReg = *pClkCtrlReg| (1<<3);
//	  //giải thích: đầu tiên tưởng tượng 1 dãy ảo với bit 0 là 1, các bit khác là 0(số lượng bit 0 sẽ
//    //phụ thuộc vào só lượng bit thanh ghi muốn cấu hình)
//    //(1<<3): dịch dãy bit tưởng tượng 3 lần: ...1000(lần 3)<-...0100(lần 2)<-...0010(lần 1)<-...0001(lần 0)
//	  //Sau khi dịch dãy bit ảo sẽ có bit 3 được set lên 1
//	  //Ta tiến hành OR dãy bit ảo này với dãy bit thanh ghi muốn cấu hình
//    //<< : dịch từ phải sang trái
//
//    //2.Cau hinh che do chan IO lam dau ra
//    //a.clear the bit 24 and 25
//    *pPortDmodeReg &= ~(3<<24) ;    //3 = 11 : set bit 24,25 về thành 00(về chế độ reset)
//
//    //b. set bit 24 len 1, cho phép cấu hình port D là output
//    *pPortDmodeReg |= (1<<24);		//dich bit cho chan 24 len 1
//
//    //3. Set chan 12 GPIO len 1 cho LED sang
//    *pPortDoutReg |= (1<<12);		//dich bit cho chan 12 len 1


	while(1);
}




