/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
/*
Address of clock control register(AHB1ENR)
0x40023800+0x30 => 	0x40023830

Address of the GPIO mode register (used to control mode)
0x40020C00 + 0x00 	=>	0x40020C00

Address of the GPIO output data register (used to write)
0x40020C00 + 0x14  =>  0x40020C14
*/


/*
 * Thiết lập phần cứng:
 * Nối chân PA0 với VDD: input = 1;
 * Nối chân PA0 với VDD: input = 0;
 * */

#include <stdint.h>

int main(void)
{
	//Khai báo cấu hình địa chỉ xung clock
    uint32_t *pClkCtrlReg = (uint32_t*)0x40023830;

    //Khai báo cấu hình các địa chỉ cần thiết thiết lập port D
    uint32_t *pPortDmodeReg = (uint32_t*)0x40020C00;
    uint32_t *pPortDoutReg = (uint32_t*)0x40020C14;

    ///Khai báo cấu hình các địa chỉ cần thiết thiết lập port A
    uint32_t *pPortAmodeReg = (uint32_t*)0x40020000 ;  //GPIOA
    uint32_t *pPortAInReg =   (uint32_t*)0x40020010 ;  //GPIOA 0x40020000 + 0x01(address offset)
    //Đây là địa chỉ cấu hình để thiết lập đọc trạng thái của các pin port A

    //II. Su dung phuong phap dich bit
    //1.Bat dong ho cho thiet bi ngoai vi GPIOD, GPOIA o AHB1ENR
    *pClkCtrlReg |= ( 1 << 3 );			//GPIOD
    *pClkCtrlReg |= ( 1 << 0 );			//GPIOA

    //2.Cau hinh che do chan IO lam dau ra
    //a.clear the bit 24 and 25  PD12 là output
    *pPortDmodeReg &= ~ ( 3 << 24 ) ;    //3 = 11 : set bit 24,25 ve 0
    //b. set bit 24 len 1
    *pPortDmodeReg |= ( 1 << 24 );		//dich bit cho chan 24 len 1

    //thiet lap PA0 input (GPIO MODE REGISTER)
    *pPortAmodeReg &= ~( 3 << 0);		//3 = 11 : set bit 0,11 về 00
    // vừa là trạng thái reset vừa là trạng thái input (xem datasheet phần GPIO port mode register)

    //Gợi ý: &(AND) : thường sẽ thay đổi tất cả trạng thái của tất cả bit
    //		 |(NOT) : chỉ thay đổi bit mà ta muốn thay đổi

    while(1)
    {
    	//doc trang thai chan PA0
    	uint8_t pinStatus = (uint8_t)(*pPortAInReg & 0x1);  //set tat ca bit khac la 0 tru bit 0 là 1
    	//lúc này việc set bit 0 lên 1 có nghĩa là yêu cầu chương trình đọc giá trị đang có tại chân PA01
    	//pPortAInReg : chứa địa chỉ mà ta đã cấu hình ban đầu là cho phép đọc chân pin của port A

		if(pinStatus)
		{
			*pPortDoutReg |= ( 1 << 12 );
		}
		else{
			*pPortDoutReg &= ~ ( 1 << 12 );
		}

    //3. Set chan 12 GPIO len 1 cho LED sang
    //*pPortDoutReg |= ( 1 << 12 );		//dich bit cho chan 12 len 1
    }
}


