/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <string.h>						//Thư viện hàm memset()
#include "stm32f407xx.h"
#include "stm32f407xx_gpio_driver.h"	//Khai báo thư viện xử lý GPIO peripheral

#define HIGH			1
#define LOW				0
#define BTN_PRESSED		HIGH
#define BTN_RELEASE		LOW

/*
 * Hàm Delay thời gian
 */
void delay(void)
{
	//for(uint32_t i = 0; i< 500000; i++);
	for(uint32_t i = 0; i< 500000/2; i++);		//giảm thời gian delay
}
/*
 * Hàm Delay thời gian
 */
void delay1(void)
{
	for(uint32_t i = 0; i< 500000; i++);
	//for(uint32_t i = 0; i< 500000/2; i++);		//giảm thời gian delay
}

int main(void)
{
	GPIOx_Handle_t Gpio_Led; 		//Khai báo biến struct chứa thông tin port và pin muốn điều khiển
	GPIOx_Handle_t Gpio_Led2; 		//Khai báo biến struct chứa thông tin port và pin muốn điều khiển
	GPIOx_Handle_t GPIOBtn;			//Khai báo biến struct chứa thông tin port và pin(input button) muốn điều khiển

	//Tách riêng 2 biến có thành phần cấu trúc giống nhau ra làm hai biến có địa chỉ riêng biệt
	memset(&Gpio_Led,0,sizeof(Gpio_Led)); 	memset(&Gpio_Led2,0,sizeof(Gpio_Led2));
	memset(&GPIOBtn,0,sizeof(GPIOBtn));

	//Cấu hình thông tin hoạt động của LED muốn điều khiển (led2)
	Gpio_Led.pGPIOx = GPIOD;										//Thiết lập port muốn điều khiển
	Gpio_Led.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;			//Chân pin của port muốn điều khiển
	Gpio_Led.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;			//Chế độ xuất tín hiệu output
	Gpio_Led.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST; 		//Tốc độ xuất tín hiệu
	Gpio_Led.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;		//Chuẩn xuất Push_Pull

	//Gpio_Led.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;		//Đầu ra ko cần điện trở kéo(dùng led nội của board)
	Gpio_Led.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU;			//Chọn pull-up(kéo lên) vì đầu ra của mạch led là GND

	//Cấu hình xung Clock cho Peripheral Port Led
	GPIO_PeriClockControl(GPIOD, ENABLE);		//Port D và Enalbe=1

	//Gọi hàm khởi tạo hoạt động cấu hình muốn điều khiển(ở đây muốn điều khiển Output Gpio_Led)
	GPIO_Init(&Gpio_Led);

	//Cấu hình thông tin hoạt động của LED muốn điều khiển (led1)
	Gpio_Led2.pGPIOx = GPIOD;										//Thiết lập port muốn điều khiển
	Gpio_Led2.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_2;			//Chân pin của port muốn điều khiển
	Gpio_Led2.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;			//Chế độ xuất tín hiệu output
	Gpio_Led2.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST; 		//Tốc độ xuất tín hiệu
	Gpio_Led2.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;		//Chuẩn xuất Push_Pull

	//Gpio_Led.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;		//Đầu ra ko cần điện trở kéo(dùng led nội của board)
	Gpio_Led2.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU;			//Chọn pull-up(kéo lên) vì đầu ra của mạch led là GND

	//Cấu hình xung Clock cho Peripheral Port Led
	GPIO_PeriClockControl(GPIOD, ENABLE);		//Port D và Enalbe=1

	//Gọi hàm khởi tạo hoạt động cấu hình muốn điều khiển(ở đây muốn điều khiển Output Gpio_Led)
	GPIO_Init(&Gpio_Led2);

	/*
	 * Vd1: Button on Board
	 */
	//Cấu hình thông tin hoạt động của Button muốn điều khiển
	/*GPIOBtn.pGPIOx = GPIOA;										//Thiết lập port muốn điều khiển
	GPIOBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;		//Chân pin của port muốn điều khiển
	GPIOBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;			//Chế độ xuất tín hiệu input
	GPIOBtn.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST; 	//Tốc độ xuất tín hiệu

	GPIOBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;		//Đầu vào ko cần điện trở kéo
	//Gpio_Led.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU;	//Chọn pull-up(kéo lên)

	//Cấu hình xung Clock cho Peripheral Port Button
	GPIO_PeriClockControl(GPIOA, ENABLE);		//Port A và Enalbe=1

	//Gọi hàm kjhởi tạo hoạt động cấu hình muốn điều khiển(ở đây muốn điều khiển Input Button)
	GPIO_Init(&GPIOBtn);*/

	/*
	 * Vd2: Button out Board
	 */
	//Cấu hình thông tin hoạt động của Button muốn điều khiển
	/*GPIOBtn.pGPIOx = GPIOB;											//Thiết lập port muốn điều khiển
	GPIOBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;			//Chân pin của port muốn điều khiển
	GPIOBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;				//Chế độ xuất tín hiệu input
	GPIOBtn.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST; 		//Tốc độ xuất tín hiệu

	//GPIOBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;		//Đầu vào ko cần điện trở kéo
	Gpio_Led.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU;			//Chọn pull-up(kéo lên) thông mạch nút nhấn

	//Cấu hình xung Clock cho Peripheral Port Button
	GPIO_PeriClockControl(GPIOB, ENABLE);		//Port B và Enalbe=1

	//Gọi hàm khởi tạo hoạt động cấu hình muốn điều khiển(ở đây muốn điều khiển Input Button)
	GPIO_Init(&GPIOBtn);*/

	/*
	 * Vd3 Button of Interrupt
	 * Chương trình chính là một led sáng tắt(led2), nút nhấn sẽ điều khiển một đèn khác(led)
	 */
	GPIOBtn.pGPIOx = GPIOB;											//Thiết lập port muốn điều khiển
	GPIOBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;			//Chân pin của port muốn điều khiển
	GPIOBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_FT;			//Chế độ xuất tín hiệu input(cạnh xuống Low)
	GPIOBtn.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST; 		//Tốc độ xuất tín hiệu

	//GPIOBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;		//Đầu vào ko cần điện trở kéo
	//Gpio_Led.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU;			//Chọn pull-up(kéo lên) thông mạch nút nhấn

	//Cấu hình xung Clock cho Peripheral Port Button
	GPIO_PeriClockControl(GPIOB, ENABLE);		//Port B và Enalbe=1

	//Gọi hàm khởi tạo hoạt động cấu hình muốn điều khiển(ở đây muốn điều khiển Input Button)
	GPIO_Init(&GPIOBtn);
	//Cấu hình IRQ15_10 configurations
	GPIO_IRQPriorityConfig(IRQ_NO_EXTI15_10, NVIC_IRQ_PRI15);			//Cấu hình mức ưu tiên
	GPIO_IRQInterruptConfig(IRQ_NO_EXTI15_10, ENABLE);					//Cấu hình interrupt NVIC


	//Vòng lặp vô hạn chương trình
	while(1)
	{
		//Vd: Nếu button đc nhấn (KO dùng ngắt)
		/*if(GPIO_ReadFromInputPin(GPIOB, GPIO_PIN_NO_12) == BTN_RELEASE)
		{
			delay();	//hàm chống dội, ngăn ngừa button de-bouncing
			GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_0); 	//Thiết lập việc sáng tắt chân pin 12 port D peripheral
		}*/

		delay();
		GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_2);
	}

	return 0;
}

/**
 * Hàm xử lý IRQ liên quan đến ngắt EXTI15_10
 */
void EXTI15_10_IRQHandler()
{
	delay();											//200ms, chống dội phím ngắt
	GPIO_IRQHangling(GPIO_PIN_NO_12);					//thiết lập ngắt(xóa cờ bit trong PR register) nếu có tín hiệu tại vị trí pin
	GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_0);			//thực hiện hàm công việc khi có ngắt xảy ra
}

//GPIOBtn.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;		//Chuẩn xuất Push_Pull
//KO sử dụng vì trường But on board vì chỉ sử dụng khi output,và vì đây là input tín hiệu

//Ko cần sử dụng điện trở kéo vì trong sở đồ nút nhấn(internal buuton) board stm32f407Disc1 đã đc thiết kế sẵn.
//Vì vậy nếu bạn sử dụng một external button thì cần phải quan tâm đến điện trở kéo
