/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/**
 * Bit Banding (V37+38)
 * ------------
 * Là khả năng thay đổi một bit của 1 value thuộc 1 địa chỉ bên trong Memory Address.
 * Tuy nhiên đây là tính năng tùy chọn. Nhà sản xuất có thể hỗ trợ hoặc không hỗ trợ tính năng này. Vì vậy bạn phải tham khảo
 * hướng dẫn sử dụng của vi điều khiển.
 *
 * Chú ý: từ khóa dùng bit banding: LDRB = Load a byte (assembly code)
 *
 * Bằng cách sử dụng tính năng Bit Banding(LDRB) thì bạn có thể thay đổi giá trị 1 bit của 1 value tại 1 địa chỉ bất kỳ một
 * cách ngay lập tức và duy nhất mà không làm ảnh hưởng đến bất kỳ bit nào khác trong value tại đại chỉ đó.
 *
 * Trong STM32F407 thì theo memory map thì bit banding hỗ trợ các phần SRAM(1 MB đầu tiên), Peripheral(1 MB đầu tiên).
 *
 * Khái niệm Bit band alias address(địa chỉ bí danh): có nghĩa là bạn có thể truy cập vào vị trí bit nào đó của vùng bit banding
 * bằng địa chỉ bí danh của vùng bit band alias và sau đó thay đổi value bit mà bạn muốn.
 * Theo memory map thì vùng bit band aliass của SRAM là 0x22000000->0x23FFFFFF(32 bit), Peripheral là 0x42000000->0x43FFFFFF(32 bit)
 * Vd: có địa chỉ Bit banding là 0x20000000 bit[0] thì có thể sử dụng vùng alias là 0x22000000 bit[0]
 *
 * Bit banding cung cấp các phép toán tử cho việc tương tác dữ liệu bit.
 *
 * Calculation of bit band alias address - Tính toán địa chỉ bí danh dải bit
 * . Tính toán địa chỉ bí danh(alias address)  bit band cho địa chỉ bộ nhớ dải bit đã cho và vị trí bit
 * . Vị trí bit thứ 7 của vị trí bộ nhớ 0x2000_0200 sử dụng địa chỉ bí danh của nó
 *
 * Công thức: Alias address = alias_base +  (32 * (bit_band_memory_addr-bit_base)) + bit * 4
 * 							  0x2200_0000 + (32 * (0x2000_02000 - 0x2200_0000))    +  7  * 4
 * Với: 0x2200_0000 : địa chỉ bit band alias cơ sở của phần SRAM -> cần dựa vào memory map để xác định phần này.
 *       0x2000_02000 : địa chỉ vị trí bit band cần thay đổi value bit
 *       7 : vị trí bit cần thay đổi value trong bit band
 *
 * Lưu ý: Tùy thuộc vào nhà phát triển mà tính năng Bit Band có đc hỗ trợ hay không, vì vậy thì khi dùng 1 dòng vi điều khiển
 * cần đọc hướng dẫn đầy đủ để xác định cách thức hoạt động mong muốn.
 * Vd: trong STM32F407 đc nhà sản xuất thiết lập tính năng ở vùng SRAM và Periphare nên khi thay đổi value bit trên các vùng
 * này thì ta có thể sử dụng tính năng Bit Band thay vì phải dùng toán tử dịch bit.
 */
/**
 * Bài tập: Cho 1 địa chỉ bit 0x2000_0200 và tiến hành sử dụng thao tác bình thường và thao thác bit banding để thay đổi
 * giá trị bit theo yêu cầu sau:
 * . Đầu tiên lưu value 0xFF vào địa chỉ 0x2000_0200
 * . Thay đổi bit thứ 7 set về value 0
 */

#include<stdint.h>

#define ALIAS_BASE   0x22000000U    //định địa chỉ cơ sở vùng bí danh

#define BITBAND_BASE 0x20000000U   //định địa chỉ cơ sở vùng bit band(vùng muốn thay đổi value bit của 1 địa chỉ nào đó)

int main(void)
{
	uint8_t *ptr = (uint8_t*)0x20000200;	//tạo và gán value địa chỉ cho con trỏ
	//0x20000200 : là địa chỉ mà tại đó bạn muốn thay đổi value của 1 vị trí bit trong value mà địa chỉ này đang chứa
	//theo yêu cầu đc đề bài.

	*ptr = 0xff;					//gán value cho value địa chỉ mà con trỏ đang chứa

	//C1: normal method - dùng cách thông thường(pp toán tử bit)
	//clearing 7th bit position - thay đổi vị trí bit thứ 7 về giá trị 0
	*ptr &= ~( 1 << 7);

	//reset to 0xff
	*ptr = 0xff;

	//C2 : bit band method - dùng phương pháp bit band tính địa chỉ alias
	uint8_t *alias_addr = (uint8_t*) (ALIAS_BASE+(32 * (0x20000200-BITBAND_BASE))+ 7 * 4);

	//Sau khi có địa chỉ alias ta có thể tiến hành việc thay đổi giá trị bit
	//clearing 7th bit of address 0x20000200
	*alias_addr = 0;  //kết quả: 0x0111_1111 = 0x7F

	//Thử chạy ở Debug -> Dùng bảng Memory browser -> nhập vị trí 0x20000200 -> chạy và xác nhận kết quả
	//Nhớ đổi hiển thị về 1 cột (chuột phải vào bảng -> column -> 4 -> chuột phải vào bảng -> cell size -> 1)

	for(;;);
}
